version: 2

project_name: gowait

builds:
  - main: ./cmd/gowait
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: [-trimpath]
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files: [LICENSE, README.md]

dockers:
  - image_templates:
      - ghcr.io/davidaparicio/gowait:{{ .Version }}-amd64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goarch: amd64
    build_flag_templates:
      - --platform=linux/amd64
  - image_templates:
      - ghcr.io/davidaparicio/gowait:{{ .Version }}-arm64
    dockerfile: Dockerfile.goreleaser
    use: buildx
    goarch: arm64
    build_flag_templates:
      - --platform=linux/arm64

docker_manifests:
  - name_template: ghcr.io/davidaparicio/gowait:{{ .Version }}
    image_templates:
      - ghcr.io/davidaparicio/gowait:{{ .Version }}-amd64
      - ghcr.io/davidaparicio/gowait:{{ .Version }}-arm64
  - name_template: ghcr.io/davidaparicio/gowait:latest
    image_templates:
      - ghcr.io/davidaparicio/gowait:{{ .Version }}-amd64
      - ghcr.io/davidaparicio/gowait:{{ .Version }}-arm64

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude: ["^docs:", "^test:", "^chore:"]
